services:
  api:
    container_name: 'api'
    build: ./api/.
    ports:
      - '8000:8000'
    volumes:
      - ./api:/app
    depends_on:
      - db
  ui:
    container_name: 'ui'
    image: node:12.16.1
    environment:
      API_URL: http://localhost:8000
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - ./ui:/app
    depends_on:
      - api
    stdin_open: true
    command: sh -c 'npm install && npm run start'
  db:
    container_name: 'db'
    image: postgres:13.4
    environment:
      POSTGRES_USER: 'dev'
      POSTGRES_PASSWORD: 'dev'
      POSTGRES_DB: 'default'
    ports:
      - 5432:5432
